### PR TITLE
Initial commit of conversion of catalog actor to graph database

### PR DESCRIPTION
**Pull request by autodidaddict**

### CODE REVIEW

**Comment by autodidaddict** [comment]
[sample_tokens.zip](https://github.com/wascc/gantry/files/4650758/sample_tokens.zip)

**Comment by brooksmtownsend** [comment]
The `start.sh` script for dynamic mode does not include the `wascc:graphdb` capability provider, this should be added for dynamic mode testing.

**Comment by autodidaddict** [comment]
> The `start.sh` script for dynamic mode does not include the `wascc:graphdb` capability provider, this should be added for dynamic mode testing.
> 
> Suggested to add:
> 
> ```
> -a ../../wascc-host/examples/.assets/libwasccgraph_redis.so \
> ```
> 
> to `start.sh`

We should include something to mention it, but remember that the redisgraph provider isn't included with the example assets. We tried to keep it out of the default stuff.

**Comment by brooksmtownsend** [comment]
> We should include something to mention it, but remember that the redisgraph provider isn't included with the example assets. We tried to keep it out of the default stuff.

I suppose referring directly to the redisgraph provider, assuming it's cloned in the same way as gantry assumes `wascc-host` is, would be an option. I end up having to just build all my own providers since I'm on Mac anyways, so I missed that it wasn't present in the example assets. Of course, running this in `freestanding` mode will alleviate the issue, but I think we should at least comment about needing the graph provider since `start.sh` fails to run

**Comment by brooksmtownsend** [comment]
Tested with latest commit, I'd say this PR is good to go and fixes #18

**Pull request merged**
